Repository Piece-iOS/Piece-iOS, pull requests merged in 2024-12, with the labels that each got.

#1 [PC-45] docs: create PR template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 📝 documentation

#2 [PIECE-33] Build: Basic Tuist settings for project
  .gitignore
  .mise.toml
  App/Project.swift
  App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  App/Resources/Assets.xcassets/Contents.json
  App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  App/Sources/ContentView.swift
  App/Sources/PieceIOSApp.swift
  Tuist.swift
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/AppContants.swift
  Tuist/ProjectDescriptionHelpers/AppEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Configuration/Configuration+configuration.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+dynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+dynamicResourceFramework.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+staticLibrary.swift
  Tuist/ProjectDescriptionHelpers/Scheme/Scheme+makeScheme.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetDependency+SPM.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetDependency+project.swift
  Workspace.swift
Labels: 👷🏻‍♀️ build

#4 [PC-211] Fix: Change font line heights in design system
  Presentation/DesignSystem/Sources/Font.swift
Labels: 🛠️ fix
