Repository Piece-iOS/Piece-iOS, pull requests merged in 2025-02, with the labels that each got.

#24 [PC-447] Feat: 앱 홈 화면 구현
  App/Sources/ContentView.swift
  Presentation/Coordinator/Project.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Sources/TabBarView.swift
  Presentation/Feature/Home/Project.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Home/Sources/HomeViewFactory.swift
  Presentation/Feature/Home/Sources/HomeViewModel.swift
  Presentation/Router/Sources/Route.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: 🪄 refactor, ✨ feature

#19 [PC-393] Feat: 카메라, 알림, 연락처 권한 요청 UI
  Domain/UseCases/Sources/Permission/CameraPermissionUseCase.swift
  Domain/UseCases/Sources/Permission/ContactsPermissionUseCase.swift
  Domain/UseCases/Sources/Permission/NotificationPermissionUseCase.swift
  Domain/UseCases/Sources/Permission/PhotoPermissionUseCase.swift
  Presentation/Feature/SignUp/Project.swift
  Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestView.swift
  Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestViewModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementViewModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebViewModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/WebView.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
Labels: ✨ feature

#29 [PC-199] 매칭 상세 - 프로필 사진 화면 구현, alert modifier 구현
  Presentation/DesignSystem/Sources/AlertView.swift
  Presentation/DesignSystem/Sources/Dimmer.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/DesignSystem/Sources/ViewModifiers/AlertModifier.swift
  Presentation/Feature/MatchingDetail/Sources/Common/MatchDetailPhotoView.swift
Labels: 🛠️ fix, ✨ feature

#31 [PC-490] 매칭 상세 화면간 navigation 작업 등
  App/Sources/ContentView.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchPhotoUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Resources/Images.xcassets/Matching-Detail-BG.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/Matching-Detail-BG.imageset/Matching-Detail-BG.png
  Presentation/DesignSystem/Sources/AlertView.swift
  Presentation/DesignSystem/Sources/Dimmer.swift
  Presentation/DesignSystem/Sources/PCTabMini.swift
  Presentation/DesignSystem/Sources/ViewModifiers/AlertModifier.swift
  Presentation/Feature/MatchingDetail/Sources/Common/BasicInfoNameView.swift
  Presentation/Feature/MatchingDetail/Sources/Common/MatchDetailPhotoView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchDetailViewFactory.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/BasicInfoModel.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickAnswerModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalk.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkViewModel.swift
Labels: 🛠️ fix, 🪄 refactor, ✨ feature

#33 [PC-502] Feat: 프로필 생성 - 가치관 Talk 기능 구현
  Data/DTO/Sources/SignUp/ValueTalksResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/ValueTalksEndpoint.swift
  Data/Repository/Sources/RepositoryFactory.swift
  Data/Repository/Sources/ValueTalks/ValueTalksRepository.swift
  Domain/RepositoryInterfaces/Sources/ValueTalks/ValueTalksRepositoryInterface.swift
  Domain/UseCases/Sources/Profile/GetValueTalksUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/TextCountIndicator.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkCard.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ViewTalkCardViewModel.swift
  Presentation/Feature/SignUp/Sources/SignUpViewFactory.swift
Labels: ✨ feature

#34 [PC-503] 프로필 생성 - 가치관Pick 입력 구현
  Data/DTO/Sources/SignUp/ValuePicksResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/ValuePicksEndpoint.swift
  Data/Repository/Sources/RepositoryFactory.swift
  Data/Repository/Sources/ValuePicks/ValuePicksRepository.swift
  Domain/RepositoryInterfaces/Sources/ValuePicksRepositoryInterface/ValuePicksRepositoryInterface.swift
  Domain/UseCases/Sources/Profile/GetProfileUseCase.swift
  Domain/UseCases/Sources/Profile/GetValuePicksUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Sources/PCToast.swift
  Presentation/DesignSystem/Sources/SelectCard.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Profile/Sources/ProfileView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickCard.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickCardViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickViewModel.swift
  Presentation/Feature/SignUp/Sources/SignUpViewFactory.swift
  Presentation/Router/Sources/Route.swift
Labels: 🛠️ fix, 🧹 chore, ✨ feature

#35 [PC-556] Feat: 매칭 상세 API 연결
  Data/DTO/Sources/Matches/MatchProfileBasicResponseDTO.swift
  Data/DTO/Sources/Matches/MatchValuePickResponseDTO.swift
  Data/DTO/Sources/Matches/MatchValuePicksResponseDTO.swift
  Data/DTO/Sources/Matches/MatchValueTalkResponseDTO.swift
  Data/DTO/Sources/Matches/MatchValueTalksResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/MatchesEndpoint.swift
  Data/Repository/Sources/Matches/MatchesRepository.swift
  Data/Repository/Sources/RepositoryFactory.swift
  Domain/Entities/Sources/MatchDetail/ProfileBasicModel.swift
  Domain/RepositoryInterfaces/Sources/MatchesRepositoryInterface/MatchesRepositoryInterface.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchProfileBasicUseCase.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchValuePickUseCase.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchValueTalkUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValuePick/ValuePickViewModel.swift
Labels: ✨ feature

#36 [PC-557] Feat: 매칭 상세 가치관Talk 퍼즐 일러스트 변경
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-01.imageset/illust-Puzzle-01.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-02.imageset/illust-Puzzle-02.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-03.imageset/illust-Puzzle-03.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-04.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-04.imageset/illust-Puzzle-04.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-05.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-05.imageset/illust-Puzzle-05.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-06.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-06.imageset/illust-Puzzle-06.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-07.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-07.imageset/illust-Puzzle-07.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-08.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-08.imageset/illust-Puzzle-08.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-09.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-09.imageset/illust-Puzzle-09.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-10.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-10.imageset/illust-Puzzle-10.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-11.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-11.imageset/illust-Puzzle-11.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-12.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-12.imageset/illust-Puzzle-12.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-13.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-13.imageset/illust-Puzzle-13.png
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
Labels: ✨ feature

#37 [PC-567] Feat: 매칭 메인에서 매칭 상세로 진입 구현
  Presentation/Feature/MatchingMain/Project.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
Labels: ✨ feature

#39 [PC-504] Feat: 스크린샷 방지 기능 도입
  App/Project.swift
  App/Sources/PieceApp.swift
  Presentation/DesignSystem/Sources/ViewModifiers/ScreenshotPreventionModifier.swift
  Presentation/Feature/Profile/Sources/ProfileView.swift
Labels: ✨ feature

#40 [PC-515] Feat: 가치관Pick 수정 기능 구현
  App/Sources/ContentView.swift
  Data/DTO/Sources/Profile/ProfileValuePickResponseDTO.swift
  Data/DTO/Sources/Profile/ProfileValuePicksResponseDTO.swift
  Data/DTO/Sources/SignUp/ValuePickAnswerResponseDTO.swift
  Data/DTO/Sources/SignUp/ValuePickRequestDTO.swift
  Data/DTO/Sources/SignUp/ValuePickResponseDTO.swift
  Data/DTO/Sources/SignUp/ValuePicksResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/ProfileEndpoint.swift
  Data/Repository/Sources/Profile/ProfileRepository.swift
  Domain/RepositoryInterfaces/Sources/Profile/ProfileRepositoryInterface.swift
  Domain/UseCases/Sources/Profile/GetMatchValuePicksUseCase.swift
  Domain/UseCases/Sources/Profile/UpdateMatchValuePicksUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Project.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Sources/Divider.swift
  Presentation/DesignSystem/Sources/NavigationBar/HomeNavigationBar.swift
  Presentation/DesignSystem/Sources/NavigationBar/NavigationBar.swift
  Presentation/Feature/EditValuePick/Project.swift
  Presentation/Feature/EditValuePick/Sources/EditValuePickView.swift
  Presentation/Feature/EditValuePick/Sources/EditValuePickViewFactory.swift
  Presentation/Feature/EditValuePick/Sources/EditValuePickViewModel.swift
  Presentation/Feature/EditValuePick/Sources/ValuePickCard.swift
  Presentation/Feature/EditValuePick/Sources/ValuePickCardModel.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Profile/Sources/ProfileView.swift
  Presentation/Router/Sources/Route.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: 🛠️ fix, ✨ feature

#41 [PC-501] Feat: 프로필 기본정보 작성 뷰 구현
  Data/PCNetwork/Sources/Endpoint/ProfileEndpoint.swift
  Data/PCNetwork/Sources/NetworkRequestType.swift
  Data/PCNetwork/Sources/NetworkService.swift
  Data/PCNetwork/Sources/Protocol/TargetType.swift
  Data/Repository/Sources/Profile/ProfileRepository.swift
  Data/Repository/Sources/RepositoryFactory.swift
  Data/Repository/Sources/SignUp/CheckNicknameRepository.swift
  Domain/Entities/Sources/Profile/ContactModel.swift
  Domain/Entities/Sources/Profile/ProfileModel.swift
  Domain/RepositoryInterfaces/Sources/Profile/ProfileRepositoryInterface.swift
  Domain/RepositoryInterfaces/Sources/SignUp/CheckNinknameRepositoryInterface.swift
  Domain/UseCases/Sources/Profile/UploadProfileImageUseCase.swift
  Domain/UseCases/Sources/SignUp/CheckNicknameUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Resources/Images.xcassets/profile-image-nodata.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/profile-image-nodata.imageset/Profile-image-nodata.svg
  Presentation/DesignSystem/Sources/DynamicTextView.swift
  Presentation/DesignSystem/Sources/PCBottomSheet.swift
  Presentation/DesignSystem/Sources/PCTextEditor.swift
  Presentation/DesignSystem/Sources/SelectCard.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CameraPicker.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ProfileCreator.swift
  Presentation/Feature/SignUp/Sources/SignUpViewFactory.swift
  Utility/PCFoundationExtension/Sources/UIImage+Extension.swift
Labels: ✨ feature

#42 [PC-586] UserDefaults 구현
  Data/LocalStorage/Sources/UserDefaults/PCUserDefaults.swift
  Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift
  Data/LocalStorage/Sources/UserDefaults/UserDefaultsKeys.swift
Labels: ✨ feature

#61 [PC-000] Fix: Endpoint.swift 파일 컴파일 오류 수정
  Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift
Labels: 🛠️ fix

#62 [PC-604] Feat: 화면 분기처리 및 카카오 로그인 탈퇴
  .gitignore
  App/Sources/PieceApp.swift
  Data/DTO/Sources/Withdraw/AppleOathTokenResponseDTO.swift
  Data/DTO/Sources/Withdraw/AppleRevokeOauthTokenRequestDTO.swift
  Data/DTO/Sources/Withdraw/WithdrawRequestDTO.swift
  Data/LocalStorage/Sources/Keychain/PCKeychain.swift
  Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift
  Data/LocalStorage/Sources/UserDefaults/UserDefaultsKeys.swift
  Data/PCNetwork/Sources/Endpoint/CommonEndpoint.swift
  Data/PCNetwork/Sources/NetworkHeader.swift
  Data/PCNetwork/Sources/NetworkService.swift
  Data/Repository/Sources/Withdraw/WithdrawRepository.swift
  Domain/RepositoryInterfaces/Sources/Withdraw/WithdrawRepositoryInterface.swift
  Domain/UseCases/Sources/Common/DeleteUserAccountUseCase.swift
  Domain/UseCases/Sources/Common/RevokeAppleOauthTokenUseCase.swift
  Presentation/DesignSystem/Project.swift
  Presentation/Feature/Login/Sources/Login/LoginViewModel.swift
  Presentation/Feature/Onboarding/Sources/OnboardingView.swift
  Presentation/Feature/Splash/Sources/SplashViewModel.swift
  Presentation/Feature/Withdraw/Project.swift
  Presentation/Feature/Withdraw/Sources/WithdrawConfirm/WithdrawConfirmViewModel.swift
  Presentation/Feature/Withdraw/Sources/WithdrawViewModel.swift
Labels: ✨ feature

#71 [PC-633] Fix: 카카오톡 앱으로 로그인 에러 해결
  App/Sources/PieceApp.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
Labels: 🛠️ fix
