Repository Piece-iOS/Piece-iOS, pull requests merged in 2025-03, with the labels that each got.

#93 [PC-679] Fix: 프로필 생성 시, 텍스트필드 Focus 미작동 및 BottomSheet 기타 custom String 누락 해결
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
Labels: 🛠️ fix

#94 [PC-000] Feat: User Role 확인 Common UseCase 생성
  Data/DTO/Sources/UserRoleResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/CommonEndpoint.swift
  Data/Repository/Sources/Common/CommonRepository.swift
  Domain/Entities/Sources/UserRoleModel.swift
  Domain/RepositoryInterfaces/Sources/Common/CommonRepositoryInterface.swift
  Domain/UseCases/Sources/Common/GetUserRoleUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
Labels: ✨ feature

#95 [PC-701] Refactor: 사용자 관련 엔드포인트, 레포지토리, 유즈케이스를 User로 리팩토링
  Data/DTO/Sources/Login/SocialLoginResponseDTO.swift
  Data/DTO/Sources/User/UserInfoResponseDTO.swift
  Data/DTO/Sources/UserRoleResponseDTO.swift
  Data/PCNetwork/Sources/Endpoint/UserEndpoint.swift
  Data/Repository/Sources/Common/CommonRepository.swift
  Data/Repository/Sources/RepositoryFactory.swift
  Data/Repository/Sources/User/UserRepository.swift
  Data/Repository/Sources/Withdraw/WithdrawRepository.swift
  Domain/Entities/Sources/Login/SocialLoginResultModel.swift
  Domain/Entities/Sources/User/ProfileStatus.swift
  Domain/Entities/Sources/User/UserInfoModel.swift
  Domain/Entities/Sources/User/UserRole.swift
  Domain/Entities/Sources/UserRoleModel.swift
  Domain/RepositoryInterfaces/Sources/Common/UserRepositoryInterface.swift
  Domain/UseCases/Sources/Common/GetServerStatusUseCase.swift
  Domain/UseCases/Sources/Common/GetUserRoleUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Domain/UseCases/Sources/User/DeleteUserAccountUseCase.swift
  Domain/UseCases/Sources/User/GetUserInfoUseCase.swift
  Domain/UseCases/Sources/User/RevokeAppleOauthTokenUseCase.swift
Labels: 🪄 refactor

#96 [PC-668] Splash 화면에서 사용자 정보를 확인하여 분기처리하는 로직 구현
  Data/DTO/Sources/Login/TokenRefreshRequestDTO.swift
  Data/DTO/Sources/Login/TokenRefreshResponseDTO.swift
  Data/PCNetwork/Sources/APIRequestInterceptor.swift
  Data/PCNetwork/Sources/Endpoint/LoginEndpoint.swift
  Domain/Entities/Sources/User/UserRole.swift
  Domain/RepositoryInterfaces/Sources/Common/UserRepositoryInterface.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/Feature/Splash/Sources/SplashView.swift
  Presentation/Feature/Splash/Sources/SplashViewFactory.swift
  Presentation/Feature/Splash/Sources/SplashViewModel.swift
Labels: ✨ feature

#97 [PC-675] Feat: role이 USER가 아닌 사용자는 프로필 탭에 진입할 수 없다
  Data/LocalStorage/Sources/UserDefaults/PCUserDefaultsService.swift
  Data/LocalStorage/Sources/UserDefaults/UserDefaultsKeys.swift
  Presentation/Feature/Home/Project.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Home/Sources/HomeViewModel.swift
  Presentation/Feature/Home/Sources/TabBarButton.swift
  Presentation/Feature/Home/Sources/TabBarView.swift
  Presentation/Feature/Home/Sources/TabBarViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/ValueTalk/ValueTalkCardViewModel.swift
  Presentation/Feature/Splash/Sources/SplashViewModel.swift
Labels: ✨ feature

#98 [PC-705] Fix: 프로필 생성 시 가치관Talk 답변이 비어있는 문제 수정
  Presentation/DesignSystem/Sources/NavigationBar/NavigationBar.swift
  Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/CreateProfileContainerViewModel.swift
Labels: 🛠️ fix

#101 [PC-494] Feat: 유저는 설정 탭에서 로그아웃을 할 수 있다
  Data/LocalStorage/Sources/Keychain/PCKeychain.swift
  Data/PCNetwork/Sources/Endpoint/SettingsEndpoint.swift
  Data/Repository/Sources/Settings/SettingsRepository.swift
  Domain/RepositoryInterfaces/Sources/Settings/SettingsRepositoryInterface.swift
  Domain/UseCases/Sources/Settings/PatchLogoutUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Home/Sources/HomeViewFactory.swift
  Presentation/Feature/Home/Sources/HomeViewModel.swift
  Presentation/Feature/Login/Sources/Login/LoginViewModel.swift
  Presentation/Feature/Login/Sources/VerifingContact/VerifingContactViewModel.swift
  Presentation/Feature/Settings/Sources/SettingsView.swift
  Presentation/Feature/Settings/Sources/SettingsViewFactory.swift
  Presentation/Feature/Settings/Sources/SettingsViewModel.swift
Labels: ✨ feature

#102 [PC-497] Feat: 매칭 화면 분기처리
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/Feature/Home/Sources/HomeView.swift
  Presentation/Feature/Home/Sources/HomeViewFactory.swift
  Presentation/Feature/Home/Sources/HomeViewModel.swift
  Presentation/Feature/Login/Sources/Login/LoginView.swift
  Presentation/Feature/Login/Sources/Login/LoginViewModel.swift
  Presentation/Feature/MatchingMain/Sources/MatchMainViewFactory.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
  Presentation/Router/Sources/Route.swift
Labels: ✨ feature

#104 [PC-725] Fix: 매칭 UI crash 문제 수정
  Presentation/DesignSystem/Sources/DynamicTextView.swift
  Presentation/DesignSystem/Sources/PCTextEditor.swift
  Presentation/Feature/MatchingMain/Sources/MatchingAnswer.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
  Presentation/Feature/MatchingMain/Sources/MatchingTimerViewModel.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
  Utility/PCFoundationExtension/Sources/DateFormatter+Extension.swift
Labels: 🛠️ fix

#112 [PC-744] Refactor: NavigationBar RightButton View 할당 방식으로 변경
  Presentation/DesignSystem/Sources/NavigationBar/NavigationBar.swift
  Presentation/DesignSystem/Sources/ViewModifiers/NavigationBarModifier.swift
  Presentation/Feature/EditValuePick/Sources/EditValuePickView.swift
  Presentation/Feature/EditValueTalk/Sources/EditValueTalkView.swift
  Presentation/Feature/MatchResult/Sources/MatchResultView.swift
  Presentation/Feature/MatchingDetail/Sources/Common/MatchDetailPhotoView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/PreviewProfile/Sources/Common/PreviewProfilePhotoView.swift
  Presentation/Feature/PreviewProfile/Sources/MatchProfileBasic/PreviewProfileBasicView.swift
  Presentation/Feature/PreviewProfile/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/PreviewProfile/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/Settings/Sources/SettingsWebView.swift
  Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift
  Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift
Labels: 🪄 refactor

#113 [PC-512] Feat: 프로필 수정 EditProfile 모듈 생성
  Data/DTO/Sources/Profile/ProfileBasicRequestDTO.swift
  Data/PCNetwork/Sources/Endpoint/ProfileEndpoint.swift
  Data/Repository/Sources/Profile/ProfileRepository.swift
  Domain/RepositoryInterfaces/Sources/Profile/ProfileRepositoryInterface.swift
  Domain/UseCases/Sources/Profile/UpdateProfileBasicUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Project.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Sources/PCTextEditor.swift
  Presentation/Feature/EditProfile/Project.swift
  Presentation/Feature/EditProfile/Sources/CameraPicker.swift
  Presentation/Feature/EditProfile/Sources/EditProfileView.swift
  Presentation/Feature/EditProfile/Sources/EditProfileViewFactory.swift
  Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
  Presentation/Feature/Profile/Sources/ProfileView.swift
  Presentation/Router/Sources/Route.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: 🛠️ fix, ✨ feature

#118 [PC-767] Fix: 잘못된 navigationBar layout 수정
  Presentation/Feature/SignUp/Sources/AvoidContactsGuide/AvoidContactsGuideView.swift
  Presentation/Feature/SignUp/Sources/PermissionRequest/PermissionRequestView.swift
Labels: 🛠️ fix

#119 [PC-768] Fix: 텍스트 필드 외 배경 선택 시 키보드 내려가지 않는 문제 수정
  Presentation/Feature/Login/Sources/VerifingContact/VerifingContactView.swift
Labels: 🛠️ fix

#120 [PC-771] Fix: 약관 웹뷰 네비게이션 레이아웃 수정 및 화면 전환
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift
Labels: 🛠️ fix

#121 [PC-772] Fix: sns bottomsheet 높이 수정 및 PCBottomSheet 수정
  Presentation/DesignSystem/Sources/PCBottomSheet.swift
  Presentation/Feature/EditProfile/Sources/EditProfileView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
Labels: 🛠️ fix

#122 [PC-773] Fix: 매칭 심사 카드 텍스트 크기 수정
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
Labels: 🛠️ fix

#124 [PC-745] Fix: 프로필 생성, 수정 화면 텍스트필드 정규식 적용
  Data/DTO/Sources/Profile/ProfileBasicResponseDTO.swift
  Presentation/Feature/EditProfile/Sources/EditProfileView.swift
  Presentation/Feature/EditProfile/Sources/EditProfileViewModel.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoView.swift
  Presentation/Feature/SignUp/Sources/CreateProfile/BasicInfo/CreateBasicInfoViewModel.swift
  Utility/PCFoundationExtension/Sources/String+Extension.swift
Labels: 🛠️ fix, ✨ feature

#126 [PC-780] Fix: 매칭 Nodata 상태 시 카드 상단 타이머 앞 텍스트 수정
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/MatchingMain/Sources/MatchingTimer.swift
Labels: 🛠️ fix, ✨ feature

#127 [PC-782] Fix: MatchingTimer 불필요한 패딩 값 제거
  Presentation/Feature/MatchingMain/Sources/MatchingTimer.swift
Labels: 🛠️ fix
