Repository Piece-iOS/Piece-iOS, pull requests merged in 2025-01, with the labels that each got.

#5 [PC-198] Feat: create Tabbar UI
  Presentation/DesignSystem/Resources/Icons.xcassets/btn-match.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/btn-match.imageset/btn-match.svg
  Presentation/DesignSystem/Sources/TabBarView.swift
Labels: ✨ feature

#10 [PC-296] 앱 bundleId, organizationName 수정
  Tuist/ProjectDescriptionHelpers/AppContants.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
Labels: 👷🏻‍♀️ build

#8 [PC-200] Feat: navigationbar UI 생성
  Presentation/DesignSystem/Sources/AlertView.swift
  Presentation/DesignSystem/Sources/MatchingAnswer.swift
  Presentation/DesignSystem/Sources/NavigationBar.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/DesignSystem/Sources/ViewModifiers/NavigationBarModifier.swift
  Presentation/Feature/MatchingMain/Project.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: ✨ feature

#7 [PC-201] Feat: Alert Component 생성
  Presentation/DesignSystem/Sources/AlertView.swift
Labels: ✨ feature

#11 [PC-301] Feat: 디자인시스템 변경사항 반영 및 추가
  Presentation/DesignSystem/Resources/Colors.xcassets/SystemError.colorset/Contents.json
  Presentation/DesignSystem/Resources/Fonts/WixMadeforDisplay-Medium.ttf
  Presentation/DesignSystem/Resources/Icons.xcassets/camera-line-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/camera-line-32.imageset/camera-line-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-20.imageset/cell-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-fill-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-fill-32.imageset/cell-line-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-line-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/cell-line-32.imageset/cell-line-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/check-24.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/check-24.imageset/check-24.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/copy-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/copy-20.imageset/copy-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/delet-circle-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/delet-circle-20.imageset/delet-circle-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/info-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/info-20.imageset/info-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/instagram-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/instagram-20.imageset/Logo-instagram-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/instagram-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/instagram-32.imageset/Logo-instagram-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-20.imageset/Logo-kakao-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-32.imageset/Logo-kakao-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-openchat-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-openchat-20.imageset/Logo-kakao-openchat-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-openchat-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/kakao-openchat-32.imageset/Logo-kakao-openchat-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/notice-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/notice-20.imageset/Notice-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/notice-40.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/notice-40.imageset/Notice-40.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/null-40.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/null-40.imageset/null-40.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/pencil-fill-24.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/pencil-fill-24.imageset/pencil-fill-24.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/pencil-line-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/pencil-line-20.imageset/pencil-line-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/photo-line-32.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/plus-24.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/plus-24.imageset/plus-24.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/plus-line-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/plus-line-20.imageset/plus-line-20.svg
  Presentation/DesignSystem/Sources/Color.swift
  Presentation/DesignSystem/Sources/Font.swift
  Presentation/DesignSystem/Sources/ViewModifiers/WixMadeforDisplay.swift
Labels: ✨ feature

#12 [PC-193] 매칭 상세 기본정보 UI 구현
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaBlack40.colorset/Contents.json
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaWhite10.colorset/Contents.json
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaWhite60.colorset/Contents.json
  Presentation/DesignSystem/Resources/Colors.xcassets/SystemError.colorset/Contents.json
  Presentation/DesignSystem/Sources/CircleButton.swift
  Presentation/DesignSystem/Sources/Color.swift
  Presentation/DesignSystem/Sources/ProfileCard.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoModel.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoView.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/Common/BasicInfoNameView.swift
Labels: ✨ feature

#13 [PC-195] 매칭 상세 가치관 Talk UI 구현
  Presentation/DesignSystem/Resources/Images.xcassets/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-01.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-01.imageset/illust-Puzzle-01.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-02.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-02.imageset/illust-Puzzle-02.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-03.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-03.imageset/illust-Puzzle-03.svg
  Presentation/DesignSystem/Sources/ObservableScrollView.swift
  Presentation/DesignSystem/Sources/PreferenceKey/ContentOffsetKey.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalk.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkViewModel.swift
Labels: ✨ feature

#6 [PC-192] Feat: create Matching Main UI
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/MatchingMain/Project.swift
  Presentation/Feature/MatchingMain/Sources/MatchingAnswer.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainView.swift
  Presentation/Feature/MatchingMain/Sources/MatchingMainViewModel.swift
  Presentation/Feature/MatchingMain/Sources/MatchingTimer.swift
  Presentation/Feature/MatchingMain/Sources/MatchingTimerViewModel.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetDependency+project.swift
  Utility/PCFoundationExtension/Project.swift
  Utility/PCFoundationExtension/Sources/DateFormatter+Extension.swift
  Workspace.swift
Labels: 👷🏻‍♀️ build, ✨ feature

#9 [PC-62] Feat: feature 모듈을 생성하는 tuist 템플릿 구현
  Tuist/ProjectDescriptionHelpers/TemplateAttributeValue+default.swift
  Tuist/Templates/feature/Project.stencil
  Tuist/Templates/feature/View.stencil
  Tuist/Templates/feature/ViewModel.stencil
  Tuist/Templates/feature/feature.swift
Labels: ✨ feature

#14 [PC-196] 매칭 상세 가치관 Pick UI 구현
  Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/photo-line-32.imageset/photo-line-32.svg
  Presentation/DesignSystem/Sources/PCTabMini.swift
  Presentation/DesignSystem/Sources/PCTextButton.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickAnswerModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickTab.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickViewModel.swift
  Tuist/Templates/feature/View.stencil
  Tuist/Templates/feature/ViewModel.stencil
Labels: ✨ feature

#15 [PC-348] Feat: 소셜 로그인, 전화번호 인증 UI 구현
  Presentation/DesignSystem/Resources/Icons.xcassets/apple-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/apple-20.imageset/apple-20.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/check-circle-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/check-circle-20.imageset/check.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/chevron-Down-24.imageset/Chevron-Down-24.svg
  Presentation/DesignSystem/Resources/Icons.xcassets/chevron-Down-24.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/google-20.imageset/Contents.json
  Presentation/DesignSystem/Resources/Icons.xcassets/google-20.imageset/google-20.svg
  Presentation/DesignSystem/Sources/MatchingAnswer.swift
  Presentation/DesignSystem/Sources/PCTextField.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/Login/Project.swift
  Presentation/Feature/Login/Sources/LoginView.swift
  Presentation/Feature/Login/Sources/LoginViewModel.swift
  Presentation/Feature/Login/Sources/VerifingContactView.swift
  Presentation/Feature/Login/Sources/VerifingContactViewModel.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
  Utility/PCFoundationExtension/Sources/Color+Extension.swift
  Utility/PCFoundationExtension/Sources/Int+Extension.swift
Labels: ✨ feature

#16 [PC-390] Build: scheme을 dev/prod에서 debug/relesase로 수정
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/AppEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Configuration/Configuration+configuration.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+dynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+dynamicResourceFramework.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+staticLibrary.swift
  Tuist/ProjectDescriptionHelpers/Scheme/Scheme+makeScheme.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetDependency+SPM.swift
Labels: 👷🏻‍♀️ build

#17 [PC-391] Feat: 회원가입 중 약관동의 UI 구현
  Presentation/Feature/SignUp/Project.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementViewModel.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: ✨ feature

#18 [PC-392] Feat: 약관 상세 웹뷰 UI 구현
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsAgreementViewModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebView.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/TermsWebViewModel.swift
  Presentation/Feature/SignUp/Sources/TermsAgreement/WebView.swift
Labels: ✨ feature

#22 [PC-77] Feat: 매칭 상세 화면
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaBlack40.colorset/Contents.json
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaWhite10.colorset/Contents.json
  Presentation/DesignSystem/Resources/Colors.xcassets/AlphaWhite60.colorset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-01.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-01.imageset/illust-Puzzle-01.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-02.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-02.imageset/illust-Puzzle-02.svg
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-03.imageset/Contents.json
  Presentation/DesignSystem/Resources/Images.xcassets/illust-Puzzle-03.imageset/illust-Puzzle-03.svg
  Presentation/DesignSystem/Sources/CircleButton.swift
  Presentation/DesignSystem/Sources/Color.swift
  Presentation/DesignSystem/Sources/ObservableScrollView.swift
  Presentation/DesignSystem/Sources/PCTabMini.swift
  Presentation/DesignSystem/Sources/PCTextButton.swift
  Presentation/DesignSystem/Sources/PreferenceKey/ContentOffsetKey.swift
  Presentation/DesignSystem/Sources/ProfileCard.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/MatchingDetail/Project.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoModel.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoView.swift
  Presentation/Feature/MatchingDetail/Sources/BasicInfo/BasicInfoViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/Common/BasicInfoNameView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchingDetailView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchingDetailViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickAnswerModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickTab.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalk.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkCard.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkViewModel.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
Labels: ✨ feature

#23 [PC-401] Feat: 앱 내비게이션 로직 구현
  App/Project.swift
  App/Sources/ContentView.swift
  App/Sources/PieceApp.swift
  App/Sources/PieceIOSApp.swift
  Domain/Entities/Project.swift
  Domain/Entities/Sources/MatchDetail/MatchProfileBasicModel.swift
  Domain/Entities/Sources/MatchDetail/MatchValuePickModel.swift
  Domain/Entities/Sources/MatchDetail/MatchValueTalkModel.swift
  Domain/Entities/Sources/MatchDetail/ValuePickModel.swift
  Domain/Entities/Sources/MatchDetail/ValueTalkModel.swift
  Domain/UseCases/Project.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchProfileBasicUseCase.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchValuePickUseCase.swift
  Domain/UseCases/Sources/MatchDetail/GetMatchValueTalkUseCase.swift
  Domain/UseCases/Sources/UseCaseFactory.swift
  Presentation/Coordinator/Project.swift
  Presentation/Coordinator/Sources/Coordinator.swift
  Presentation/DesignSystem/Project.swift
  Presentation/DesignSystem/Sources/PCTextField.swift
  Presentation/DesignSystem/Sources/RoundedButton.swift
  Presentation/Feature/MatchingDetail/Project.swift
  Presentation/Feature/MatchingDetail/Sources/MatchDetailViewFactory.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/BasicInfoModel.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchProfileBasic/MatchProfileBasicViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/MatchingDetailView.swift
  Presentation/Feature/MatchingDetail/Sources/MatchingDetailViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickView.swift
  Presentation/Feature/MatchingDetail/Sources/ValuePick/ValuePickViewModel.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkView.swift
  Presentation/Feature/MatchingDetail/Sources/ValueTalk/ValueTalkViewModel.swift
  Presentation/Router/Project.swift
  Presentation/Router/Sources/Route.swift
  Presentation/Router/Sources/Router.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Modules.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+app.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetDependency+SPM.swift
Labels: 🛠️ fix, 👷🏻‍♀️ build, ✨ feature
